services:
  - type: web
    name: hotel-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd hotel-frontend && npm install && npm run build
    staticPublishPath: ./hotel-frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
